title: Szkoła Rzeczypospolitych: kurs z metod numerycznych część 1
description: Cele zajęć jest nauczenie się znajdowania rozwiązań problemów
zdefiniowanych modelem matematycznym za pomocą modelu obliczeniowego w postaci programu komputerowego.
show_downloads: true
theme: jekyll-theme-architect
