title: The School of Commonwealths data science course 
description: Teach data science and enhance students' capacity to think critically and cooperate globally within the School of Commonwealths
show_downloads: true
theme: jekyll-theme-architect
